name: testing web

on: [push]

jobs:
  apicafe_io:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Scan TestSite
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: 'https://admin.101pay.io'
