name: testing web

on: [push]

jobs:
  apicafe_io:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Scan TesingSite
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: 'https://dakohubsuptest.web.app'
